version: "3.9"
services:
  api:
    image: cnbian/laobian-api:latest
    volumes:
      - ${ENV_API_ASSET_LOCATION}:/asset
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5010
      - ASPNETCORE_ENVIRONMENT
      - ENV_API_Source
      - ENV_API_AssetLocation=/asset
      - ENV_API_GitHubDbRepoApiToken
      - ENV_API_GitHubDbRepoUserName
      - ENV_API_GitHubDbRepoName
      - ENV_API_GitHubDbRepoBranchName
      - ENV_API_GitHubBlogPostRepoApiToken
      - ENV_API_GitHubBlogPostRepoUserName
      - ENV_API_GitHubBlogPostRepoName
      - ENV_API_GitHubBlogPostRepoBranchName
      - ENV_API_CommandLineApp
      - ENV_API_CommandLineBeginArg
  admin:
    image: cnbian/laobian-admin:latest
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5011
      - ASPNETCORE_ENVIRONMENT
      - ENV_ADMIN_ApiLocalEndPoint=http://api:5010
      - ENV_ADMIN_BlogRemoteEndPoint
      - ENV_ADMIN_AdminName
      - ENV_ADMIN_AdminPassword
    ports:
      - "5011:5011"
    depends_on:
      - api
  blog:
    image: cnbian/laobian-blog:latest
    volumes:
      - ${ENV_BLOG_ASSET_LOCATION}:/asset
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5012
      - ASPNETCORE_ENVIRONMENT
      - ENV_BLOG_ApiLocalEndPoint=http://api:5010
      - ENV_BLOG_PotsPerPage
      - ENV_BLOG_AdminEmail
      - ENV_BLOG_AdminChineName
      - ENV_BLOG_AdminEnglishName
      - ENV_BLOG_AssetLOcation=/asset
    ports:
      - "5012:5012"
    depends_on:
      - api