version: "3.9"
services:
  api:
    image: cnbian/laobian-api:${ENV_APP_VERSION}
    volumes:
      - ${ENV_ASSET_LOCATION}:/asset
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5011
      - ASPNETCORE_ENVIRONMENT
      - ENV_BLOG_LOCAL_ENDPOINT=http://blog:5013
      - ENV_BLOG_REMOTE_ENDPOINT
      - ENV_FILE_REMOTE_ENDPOINT
      - ENV_ADMIN_USER_NAME
      - ENV_ADMIN_EMAIL
      - ENV_ASSET_LOCATION=/asset
      - ENV_ADMIN_CHINESE_NAME
      - ENV_ADMIN_ENGLISH_NAME
      - ENV_SEND_GRID_API_KEY
      - ENV_DATA_PROTECTION_KEY_PATH=/asset/data_protection
      - ENV_HTTP_REQUEST_TOKEN
      - ENV_COMMAND_LINE_APP
      - ENV_COMMAND_LINE_BEGIN_ARG
      - ENV_GITHUB_DB_REPO_API_TOKEN
      - ENV_GITHUB_DB_REPO_BRANCH_NAME
      - ENV_GITHUB_DB_REPO_NAME
      - ENV_GITHUB_DB_REPO_USER_NAME
  admin:
    image: cnbian/laobian-admin:${ENV_APP_VERSION}
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5012
      - ASPNETCORE_ENVIRONMENT
      - ENV_BLOG_LOCAL_ENDPOINT=http://blog:5013
      - ENV_API_LOCAL_ENDPOINT=http://api:5011
      - ENV_BLOG_REMOTE_ENDPOINT
      - ENV_FILE_REMOTE_ENDPOINT
      - ENV_ADMIN_USER_NAME
      - ENV_ADMIN_EMAIL
      - ENV_ASSET_LOCATION=/asset
      - ENV_ADMIN_CHINESE_NAME
      - ENV_ADMIN_ENGLISH_NAME
      - ENV_SEND_GRID_API_KEY
      - ENV_DATA_PROTECTION_KEY_PATH=/asset/data_protection
      - ENV_HTTP_REQUEST_TOKEN
      - ENV_ADMIN_PASSWORD
    ports:
      - "${ENV_ADMIN_PORT}:5012"
    depends_on:
      - api
  blog:
    image: cnbian/laobian-blog:${ENV_APP_VERSION}
    volumes:
      - ${ENV_ASSET_LOCATION}:/asset
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5013
      - ASPNETCORE_ENVIRONMENT
      - ENV_API_LOCAL_ENDPOINT=http://api:5011
      - ENV_BLOG_REMOTE_ENDPOINT
      - ENV_FILE_REMOTE_ENDPOINT
      - ENV_ADMIN_USER_NAME
      - ENV_ADMIN_EMAIL
      - ENV_ASSET_LOCATION=/asset
      - ENV_ADMIN_CHINESE_NAME
      - ENV_ADMIN_ENGLISH_NAME
      - ENV_SEND_GRID_API_KEY
      - ENV_DATA_PROTECTION_KEY_PATH=/asset/data_protection
      - ENV_HTTP_REQUEST_TOKEN
      - ENV_POSTS_PER_PAGE
    ports:
      - "${ENV_BLOG_PORT}:5013"
    depends_on:
      - api