name: 5.0

on:
  push:
    branches: [ 5.0 ]

jobs:
  publish_to_docker:
    name: Build and Push Docker image
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y libxml2-utils

      - name: Setup environment variables
        run: |
          APP_VERSION=`xmllint --xpath "/Project/PropertyGroup/Version/text()" Directory.Build.props`
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push API
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: |
            cnbian/laobian-api:${{ env.APP_VERSION }}
            ghcr.io/jerrybian/laobian-api:${{ env.APP_VERSION }}

      - name: Build and Push ADMIN
        id: docker_build_admin
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.admin
          push: true
          tags: |
            cnbian/laobian-admin:${{ env.APP_VERSION }}
            ghcr.io/jerrybian/laobian-admin:${{ env.APP_VERSION }}

      - name: Build and Push BLOG
        id: docker_build_blog
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.blog
          push: true
          tags: |
            cnbian/laobian-blog:${{ env.APP_VERSION }}
            ghcr.io/jerrybian/laobian-blog:${{ env.APP_VERSION }}
      
      - name: deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /laobian/script/v5
            sh deploy-stage.sh stage ${{ env.APP_VERSION }}