name: master

on:
  push:
    branches: [ master ]

jobs:
  publish_api:
    name: Publish API images
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y libxml2-utils

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup environment variables
        run: |
          APP_VERSION=`xmllint --xpath "/Project/PropertyGroup/Version/text()" Directory.Build.props`
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Build and push API images
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: |
            cnbian/laobian-api:latest
            cnbian/laobian-api:${{ env.APP_VERSION }}
            ghcr.io/jerrybian/laobian-api:latest
            ghcr.io/jerrybian/laobian-api:${{ env.APP_VERSION }}

  publish_admin:
    name: Publish ADMIN images
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y libxml2-utils

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup environment variables
        run: |
          APP_VERSION=`xmllint --xpath "/Project/PropertyGroup/Version/text()" Directory.Build.props`
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Build and push ADMIN images
        id: docker_build_admin
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.admin
          push: true
          tags: |
            cnbian/laobian-admin:latest
            cnbian/laobian-admin:${{ env.APP_VERSION }}
            ghcr.io/jerrybian/laobian-admin:latest
            ghcr.io/jerrybian/laobian-admin:${{ env.APP_VERSION }}

  publish_blog:
    name: Publish BLOG images
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y libxml2-utils

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup environment variables
        run: |
          APP_VERSION=`xmllint --xpath "/Project/PropertyGroup/Version/text()" Directory.Build.props`
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Build and push BLOG images
        id: docker_build_blog
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.blog
          push: true
          tags: |
            cnbian/laobian-blog:latest
            cnbian/laobian-blog:${{ env.APP_VERSION }}
            ghcr.io/jerrybian/laobian-blog:latest
            ghcr.io/jerrybian/laobian-blog:${{ env.APP_VERSION }}

  # deploy_server:
  #   name: Deploy to remote server
  #   runs-on: ubuntu-20.04
  #   needs: [publish_api, publish_admin, publish_blog]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get install -y libxml2-utils

  #     - name: Setup environment variables
  #       run: |
  #         APP_VERSION=`xmllint --xpath "/Project/PropertyGroup/Version/text()" Directory.Build.props`
  #         echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

  #     - name: deploy server
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.VPS_SSH_HOST }}
  #         username: ${{ secrets.VPS_SSH_USER }}
  #         password: ${{ secrets.VPS_SSH_PASSWORD }}
  #         port: ${{ secrets.VPS_SSH_PORT }}
  #         script: |
  #           sh /ga/deploy-laobian.sh prod ${{ env.APP_VERSION }}