name: v12.0

on:
  push:
    branches: [ v12.0 ]

jobs:
  publish_docker_image:
    name: Publish Docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup environment variables
        run: |
          APP_VERSION=`cat VERSION`
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker images
        id: docker_build_image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            ver=${{ env.APP_VERSION }}
          tags: |
            cnbian/swan:stage
            ghcr.io/jerrybian/swan:stage

  deploy_server:
    name: Deploy to remote server
    runs-on: ubuntu-latest
    needs: [publish_docker_image]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: |
          APP_VERSION=`cat VERSION`
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sh /ga/script/deploy-swan-stage.sh ${{ env.APP_VERSION }}